name: CF Devops

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 18

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run the Java application
        run: java -cp target/my-app-1.0-SNAPSHOT.jar maven.Hello

      - name: List the current directory (for debugging)
        run: ls -a
