name: CF Devops

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 18

      - name: Build with Maven
        run: mvn -B package --file pom.xml | tee maven-output.txt

      - name: Display Maven build output
        run: cat maven-output.txt

      - name: Run the Java application
        run: java -cp target/my-app-1.0-SNAPSHOT.jar maven.Hello | tee hello-output.txt

      - name: Display Java application output
        run: cat hello-output.txt

      - name: List the current directory
        run: ls -a

